### ISSUE TITLE
Clean up return types of AsyncClient::browse()/browse_many()

### ISSUE THREAD

**Issue by sgoll** [HMIProject/open62541#59]
There is a discrepancy between `AsyncClient::browse()` and `browse_many()` here: the former turns invalid OPC UA arrays into `Err` while the latter passes this through as `None`. I would like to clean this up anyway.

In fact, I don't think that an invalid array should be possible here, at least the specs don't seem to mention it in [BrowseResult](https://reference.opcfoundation.org/Core/Part4/v104/docs/7.3) components.

_Originally posted by @sgoll in https://github.com/HMIProject/open62541/issues/58#issuecomment-1978452528_

**Comment by uklotzde** [comment]
> @uklotzde What should be the return type of `browse_many()`? Bubble up inner errors into the single `Result` or nest the `Result`s inside each other?

The latter would be more consistent.Results for different nodes are independent of each other and should not be mixed. The failed browse operation for a single node should not affect the results for other nodes.

The outer `Result` is only for the batch operation for errors that affect all nodes.
